// Question Bank — JEE-Style Mock Test (Class XII CS)
// 120 questions across 4 topics

const QUESTION_BANK = {
  topic1: {
    name: "Revision of Python (Class XI)",
    questions: [
      {
        q: "Which of the following is an <b>immutable</b> data type in Python?",
        options: ["List", "Dictionary", "Tuple", "Set"],
        answer: 2,
        explain: "Tuples are immutable — once created, their elements cannot be changed.",
        diff: "E",
      },
      {
        q: "What is the output of <code>type(3.0)</code> in Python?",
        options: ["&lt;class 'int'>", "&lt;class 'float'>", "&lt;class 'double'>", "&lt;class 'number'>"],
        answer: 1,
        explain: "<code>3.0</code> is a floating-point literal, so <code>type()</code> returns float.",
        diff: "E",
      },
      {
        q: "Which operator is used for <b>integer (floor) division</b> in Python?",
        options: ["/", "//", "%", "**"],
        answer: 1,
        explain: "<code>//</code> performs floor (integer) division, returning the quotient without the remainder.",
        diff: "E",
      },
      {
        q: 'The expression <code>"Hello" * 3</code> evaluates to:',
        options: ['"HelloHelloHello"', '"Hello3"', "Error: TypeError", '"Hello Hello Hello"'],
        answer: 0,
        explain: "Multiplying a string by an integer n repeats it n times.",
        diff: "E",
      },
      {
        q: "Which of the following is used to take input from the user in Python?",
        options: ["input()", "scan()", "read()", "get()"],
        answer: 0,
        explain: "<code>input()</code> reads a line from standard input and returns it as a string.",
        diff: "E",
      },
      {
        q: "Which data type in Python stores key-value pairs?",
        options: ["List", "Tuple", "Set", "Dictionary"],
        answer: 3,
        explain: "A dictionary (<code>dict</code>) is a mapping of unique keys to values.",
        diff: "E",
      },
      {
        q: "<pre>print(10 % 3)</pre>What is the output?",
        options: ["3", "1", "0", "3.33"],
        answer: 1,
        explain: "<code>%</code> is the modulus operator. 10 ÷ 3 = 3 remainder <b>1</b>.",
        diff: "E",
      },
      {
        q: "<pre>print(len(\"Computer Science\"))</pre>What is the output?",
        options: ["15", "16", "17", "18"],
        answer: 2,
        explain: "‘Computer Science’ has 17 characters including the space.",
        diff: "E",
      },
      {
        q: "Which of the following is the correct way to create an empty dictionary?",
        options: ["d = []", "d = {}", "d = ()", "d = set()"],
        answer: 1,
        explain: "<code>{}</code> creates an empty dict. <code>[]</code> is a list, <code>()</code> is a tuple, <code>set()</code> is an empty set.",
        diff: "E",
      },
      {
        q: "Which keyword is used to exit a loop prematurely in Python?",
        options: ["exit", "quit", "break", "stop"],
        answer: 2,
        explain: "<code>break</code> terminates the nearest enclosing loop.",
        diff: "E",
      },
      {
        q: "The value of the expression <code>bool(0)</code> is:",
        options: ["True", "False", "0", "None"],
        answer: 1,
        explain: "In Python, <code>0</code> is considered <i>falsy</i>, so <code>bool(0)</code> returns <code>False</code>.",
        diff: "E",
      },
      {
        q: "Which function converts a string to an integer in Python?",
        options: ["str()", "int()", "float()", "chr()"],
        answer: 1,
        explain: "<code>int(string)</code> converts a numeric string to an integer.",
        diff: "E",
      },
      {
        q: "<pre>for i in range(2, 10, 2):\n    print(i, end=' ')</pre>What is the output?",
        options: ["2 4 6 8", "2 4 6 8 10", "0 2 4 6 8", "2 4 6 8 10 12"],
        answer: 0,
        explain: "<code>range(2, 10, 2)</code> yields 2, 4, 6, 8 (stop value 10 is exclusive).",
        diff: "M",
      },
      {
        q: "<pre>s = \"PYTHON\"\nprint(s[1:4])</pre>What is the output?",
        options: ["PYT", "YTH", "YTHO", "Pyth"],
        answer: 1,
        explain: "Indices 1 to 3 (slice stop exclusive) → <code>'YTH'</code>.",
        diff: "M",
      },
      {
        q: "<pre>a = [10, 20, 30, 40, 50]\nprint(a[-2])</pre>What is the output?",
        options: ["20", "30", "40", "50"],
        answer: 2,
        explain: "<code>-2</code> is the second-to-last element, which is 40.",
        diff: "M",
      },
      {
        q: "<pre>d = {\"a\": 1, \"b\": 2, \"c\": 3}\nprint(d.get(\"d\", 0))</pre>What is the output?",
        options: ["None", "KeyError", "0", '"d"'],
        answer: 2,
        explain: "<code>get()</code> returns the default value <code>0</code> when key is missing instead of raising KeyError.",
        diff: "M",
      },
      {
        q: "<pre>i = 0\nwhile i < 5:\n    i += 1\n    if i == 3:\n        continue\n    print(i, end=' ')</pre>What is the output?",
        options: ["1 2 3 4 5", "1 2 4 5", "1 2 4", "1 2 3 4"],
        answer: 1,
        explain: "<code>continue</code> skips the print when i==3, so 3 is omitted: 1 2 4 5.",
        diff: "M",
      },
      {
        q: "<pre>print(\"Hello\"[::-1])</pre>What is the output?",
        options: ["Hello", "olleH", "Error", "H"],
        answer: 1,
        explain: "<code>[::-1]</code> reverses the string → <code>'olleH'</code>.",
        diff: "M",
      },
      {
        q: "<pre>t = (1, 2, 3, 4)\nprint(t[1] + t[3])</pre>What is the output?",
        options: ["4", "5", "6", "Error"],
        answer: 2,
        explain: "<code>t[1]=2</code> and <code>t[3]=4</code>. Their sum is 6.",
        diff: "M",
      },
      {
        q: "<pre>a = [1, 2, 3]\nb = a\nb.append(4)\nprint(a)</pre>What is the output?",
        options: ["[1, 2, 3]", "[1, 2, 3, 4]", "[4]", "Error"],
        answer: 1,
        explain: "<code>b = a</code> makes both refer to the same list, so appending to b also modifies a.",
        diff: "M",
      },
      {
        q: 'What is the result of the expression <code>"abc" + str(123)</code>?',
        options: ['"abc123"', '"abc+123"', "Error: TypeError", "426"],
        answer: 0,
        explain: "<code>+</code> on two strings performs concatenation. <code>str(123)</code> converts the int first.",
        diff: "M",
      },
      {
        q: "<pre>s = {1, 2, 3, 3, 2}\nprint(len(s))</pre>What is the output?",
        options: ["5", "4", "3", "2"],
        answer: 2,
        explain: "Sets store unique elements, so duplicates are removed: {1,2,3} has length 3.",
        diff: "M",
      },
      {
        q: "<pre>x = 5\ny = 2\nprint(x ** y / y)</pre>What is the output?",
        options: ["12.0", "12.5", "25.0", "Error"],
        answer: 1,
        explain: "<code>**</code> has higher precedence than <code>/</code>. So <code>5**2 = 25</code>, then 25/2 = 12.5.",
        diff: "M",
      },
      {
        q: "<pre>for ch in \"AI\":\n    print(ch * 2, end='-')</pre>What is the output?",
        options: ["A-I-", "AA-II-", "AI-AI-", "AA-II"],
        answer: 1,
        explain: "Each character is duplicated and printed with a hyphen separator: AA-II-.",
        diff: "M",
      },
      {
        q: "<pre>a = [1, 2, 3]\nb = a[:]\nb[0] = 99\nprint(a, b)</pre>What is the output?",
        options: ["[99, 2, 3] [99, 2, 3]", "[1, 2, 3] [99, 2, 3]", "[1, 2, 3] [1, 2, 3]", "Error"],
        answer: 1,
        explain: "<code>a[:]</code> creates a <i>shallow copy</i>, so b is independent of a.",
        diff: "H",
      },
      {
        q: "<pre>d = {}\nd[1] = 'a'\nd[True] = 'b'\nprint(len(d))</pre>What is the output?",
        options: ["2", "1", "0", "Error"],
        answer: 1,
        explain: "In Python, <code>1 == True</code>, so the second assignment overwrites the first. Length is 1.",
        diff: "H",
      },
      {
        q: "<pre>print(2 ** 3 ** 2)</pre>What is the output?",
        options: ["36", "64", "512", "216"],
        answer: 2,
        explain: "<code>**</code> is right-associative: <code>2 ** (3 ** 2) = 2 ** 9 = 512</code>, not 64.",
        diff: "H",
      },
      {
        q: "<pre>x = \"Hello\"\nprint(x.replace('l', 'L', 1))</pre>What is the output?",
        options: ["HeLLo", "HELLo", "HeLlo", "Hello"],
        answer: 2,
        explain: "<code>replace(old, new, count)</code> with count=1 replaces only the first occurrence: <code>HeLlo</code>.",
        diff: "H",
      },
      {
        q: "<pre>a = [10, 20, 30]\nprint(a * 2)</pre>What is the output?",
        options: ["[20, 40, 60]", "[10, 20, 30, 10, 20, 30]", "[10, 20, 30, 2]", "Error"],
        answer: 1,
        explain: "List * n concatenates the list with itself n times.",
        diff: "H",
      },
      {
        q: "<pre>print(' '.join(['Python', 'is', 'fun']))</pre>What is the output?",
        options: ["Pythonisfun", "Python-is-fun", "Python is fun", "Error"],
        answer: 2,
        explain: "<code>str.join(list)</code> joins elements of an iterable with the string as separator.",
        diff: "H",
      },
    ],
  },
  topic2: {
    name: "Exception Handling",
    questions: [
      {
        q: "Which keyword is used to handle exceptions in Python?",
        options: ["if", "catch", "try", "handle"],
        answer: 2,
        explain: "Python uses <code>try/except</code> (not try/catch like Java/C++).",
        diff: "E",
      },
      {
        q: "Which block is executed <b>only if no exception occurs</b> in the <code>try</code> block?",
        options: ["except", "else", "finally", "default"],
        answer: 1,
        explain: "<code>else</code> runs only when the <code>try</code> block succeeds without an exception.",
        diff: "E",
      },
      {
        q: "Which block in Python exception handling is <b>always executed</b>, regardless of whether an exception occurs?",
        options: ["try", "except", "else", "finally"],
        answer: 3,
        explain: "<code>finally</code> always runs — used for cleanup like closing files.",
        diff: "E",
      },
      {
        q: "Which exception is raised when a division by zero occurs in Python?",
        options: ["ValueError", "ZeroDivisionError", "ArithmeticError", "MathError"],
        answer: 1,
        explain: "<code>ZeroDivisionError</code> is raised for integer/float division by zero.",
        diff: "E",
      },
      {
        q: "Which exception is raised when a variable is referenced before it is defined?",
        options: ["NameError", "TypeError", "ValueError", "IndexError"],
        answer: 0,
        explain: "<code>NameError</code> is raised for unbound (undefined) names.",
        diff: "E",
      },
      {
        q: 'Which is the correct syntax to raise an exception explicitly?',
        options: ['throw ValueError("Error")', 'raise ValueError("Error")', 'error ValueError("Error")', 'exception ValueError("Error")'],
        answer: 1,
        explain: "Python uses <code>raise</code> to explicitly throw an exception.",
        diff: "E",
      },
      {
        q: "Which exception is raised when an incorrect type is used in an operation?",
        options: ["TypeError", "ValueError", "SyntaxError", "IndexError"],
        answer: 0,
        explain: "<code>TypeError</code> occurs when an operation is applied to an object of inappropriate type.",
        diff: "E",
      },
      {
        q: "Which exception is raised when a list index is out of range?",
        options: ["IndexError", "ValueError", "TypeError", "KeyError"],
        answer: 0,
        explain: "<code>IndexError</code> is raised when a sequence subscript is out of range.",
        diff: "E",
      },
      {
        q: "Which exception is raised when a dictionary key is not found?",
        options: ["IndexError", "KeyError", "ValueError", "NameError"],
        answer: 1,
        explain: "<code>KeyError</code> is raised when a dict key is missing.",
        diff: "E",
      },
      {
        q: "Which exception is raised when input data is of correct type but inappropriate value?",
        options: ["TypeError", "ValueError", "NameError", "IOError"],
        answer: 1,
        explain: "<code>ValueError</code> is raised when a function receives an argument of correct type but invalid value.",
        diff: "E",
      },
      {
        q: "What is the keyword used to define a custom exception class in Python?",
        options: ["class", "def", "exception", "struct"],
        answer: 0,
        explain: "Custom exceptions are defined as classes that inherit from <code>Exception</code>.",
        diff: "E",
      },
      {
        q: "What is the base class for <b>all built-in exceptions</b> in Python?",
        options: ["Exception", "BaseException", "Error", "Throwable"],
        answer: 1,
        explain: "<code>BaseException</code> is the root of the exception hierarchy. <code>Exception</code> inherits from it.",
        diff: "E",
      },
      {
        q: "<pre>try:\n    print(10 / 2)\nexcept:\n    print(\"Error\")\nelse:\n    print(\"Done\")</pre>What is the output?",
        options: ["5.0", "5.0 Done", "Error", "Done Error"],
        answer: 1,
        explain: "No exception → try block prints 5.0, then else prints Done.",
        diff: "M",
      },
      {
        q: "<pre>try:\n    x = int(\"abc\")\nexcept ValueError:\n    print(\"V\")\nexcept:\n    print(\"E\")</pre>What is the output?",
        options: ["V", "E", "V E", "VE"],
        answer: 0,
        explain: "<code>int('abc')</code> raises <code>ValueError</code>, caught by the first except.",
        diff: "M",
      },
      {
        q: "<pre>try:\n    print(\"Hello\")\nexcept:\n    print(\"Except\")\nfinally:\n    print(\"Finally\")</pre>What is the output?",
        options: ["Hello", "Hello Except", "Hello Finally", "Hello Except Finally"],
        answer: 2,
        explain: "No exception → try runs, finally always runs.",
        diff: "M",
      },
      {
        q: "<pre>try:\n    print(1/0)\nexcept ZeroDivisionError:\n    print(\"Z\")\nfinally:\n    print(\"F\")</pre>What is the output?",
        options: ["Z", "F", "Z F", "F Z"],
        answer: 2,
        explain: "ZeroDivisionError → prints Z. Then finally → prints F.",
        diff: "M",
      },
      {
        q: "<pre>try:\n    lst = [1, 2]\n    print(lst[5])\nexcept IndexError:\n    print(\"I\")\nexcept Exception:\n    print(\"E\")</pre>What is the output?",
        options: ["I", "E", "IE", "Error"],
        answer: 0,
        explain: "IndexError is caught by the first matching handler.",
        diff: "M",
      },
      {
        q: "<pre>try:\n    raise ValueError(\"Bad value\")\nexcept ValueError as e:\n    print(str(e))</pre>What is the output?",
        options: ["Bad value", "ValueError", "e", "Error"],
        answer: 0,
        explain: "<code>str(e)</code> gives the exception message 'Bad value'.",
        diff: "M",
      },
      {
        q: "<pre>try:\n    x = 5 + \"abc\"\nexcept TypeError:\n    print(\"Type\")\nexcept:\n    print(\"Other\")</pre>What is the output?",
        options: ["Type", "Other", "Type Other", "Error"],
        answer: 0,
        explain: "int + str raises TypeError, caught by the first except.",
        diff: "M",
      },
      {
        q: "<pre>try:\n    a = int(\"10\")\n    b = int(\"20\")\nexcept:\n    print(\"E\")\nelse:\n    print(a + b)</pre>What is the output?",
        options: ["10", "20", "30", "E"],
        answer: 2,
        explain: "No exception → else runs and prints 10+20 = 30.",
        diff: "M",
      },
      {
        q: "<pre>try:\n    f = open(\"nofile.txt\")\nexcept FileNotFoundError:\n    print(\"FNF\")\nexcept IOError:\n    print(\"IO\")</pre>What is the output?",
        options: ["FNF", "IO", "FNF IO", "Error"],
        answer: 0,
        explain: "FileNotFoundError is a subclass of OSError/IOError; the more specific handler runs first.",
        diff: "M",
      },
      {
        q: "<pre>def check(n):\n    if n < 0:\n        raise ValueError(\"Negative\")\n    return n\ntry:\n    print(check(-5))\nexcept ValueError as v:\n    print(v)</pre>What is the output?",
        options: ["-5", "Negative", "ValueError", "Error"],
        answer: 1,
        explain: "check(-5) raises ValueError, which is caught and the message 'Negative' is printed.",
        diff: "M",
      },
      {
        q: "<pre>try:\n    print(\"a\")\n    raise Exception(\"b\")\n    print(\"c\")\nexcept:\n    print(\"d\")\nfinally:\n    print(\"e\")</pre>What is the output?",
        options: ["a b c d e", "a d e", "a c d e", "a b d e"],
        answer: 1,
        explain: "Prints 'a', raises exception (skipping 'c'), then 'd' from except, then 'e' from finally.",
        diff: "M",
      },
      {
        q: "<pre>try:\n    x = 10\n    print(x)\nexcept:\n    print(\"Except\")\nelse:\n    print(\"No Error\")</pre>What is the output?",
        options: ["10", "10 Except", "10 No Error", "10 Except No Error"],
        answer: 2,
        explain: "No exception → try prints 10, else prints 'No Error'.",
        diff: "M",
      },
      {
        q: "<pre>try:\n    try:\n        print(1/0)\n    except ValueError:\n        print(\"V\")\n    finally:\n        print(\"F1\")\nexcept:\n    print(\"F2\")</pre>What is the output?",
        options: ["V", "F1", "F1 F2", "V F1 F2"],
        answer: 2,
        explain: "Inner except doesn't match (ZeroDivisionError ≠ ValueError). Inner finally prints 'F1'. Outer except catches it → prints 'F2'.",
        diff: "H",
      },
      {
        q: "<pre>def func():\n    try:\n        return 1\n    finally:\n        return 2\nprint(func())</pre>What is the output?",
        options: ["1", "2", "1 2", "Error"],
        answer: 1,
        explain: "A <code>return</code> in <code>finally</code> overrides the <code>return</code> in <code>try</code>.",
        diff: "H",
      },
      {
        q: "<pre>class MyError(Exception):\n    pass\ntry:\n    raise MyError(\"Custom\")\nexcept Exception as e:\n    print(type(e).__name__)</pre>What is the output?",
        options: ["Exception", "MyError", "Custom", "Error"],
        answer: 1,
        explain: "<code>type(e).__name__</code> gives the actual class name of the exception instance.",
        diff: "H",
      },
      {
        q: "<pre>try:\n    x = 5\n    if x > 0:\n        raise Exception(\"Pos\")\nexcept Exception as e:\n    print(\"Caught:\", e)\nprint(\"End\")</pre>What is the output?",
        options: ["Caught: Pos End", "Caught: Pos", "End", "Error"],
        answer: 0,
        explain: "Exception caught and printed, then 'End' after the try/except block.",
        diff: "H",
      },
      {
        q: "<pre>try:\n    print(\"Try\")\nexcept:\n    print(\"Except\")\nelse:\n    print(\"Else\")\nfinally:\n    print(\"Finally\")</pre>What is the output?",
        options: ["Try", "Try Else", "Try Else Finally", "Try Except Finally"],
        answer: 2,
        explain: "No exception → try, else, finally all run.",
        diff: "H",
      },
      {
        q: "<pre>try:\n    d = {\"a\": 1}\n    print(d[\"b\"])\nexcept KeyError:\n    print(\"K\")\nfinally:\n    print(\"F\")\nprint(\"End\")</pre>What is the output?",
        options: ["K", "K F", "K F End", "F End"],
        answer: 2,
        explain: "KeyError → 'K' from except, 'F' from finally, 'End' after the block.",
        diff: "H",
      },
    ],
  },
  topic3: {
    name: "Functions in Python",
    questions: [
      {
        q: "Which keyword is used to define a function in Python?",
        options: ["function", "def", "fun", "define"],
        answer: 1,
        explain: "Python uses <code>def</code> to define a function.",
        diff: "E",
      },
      {
        q: "What is the term for a variable defined <b>inside</b> a function?",
        options: ["Global variable", "Local variable", "Built-in variable", "Public variable"],
        answer: 1,
        explain: "Variables defined inside a function are local to that function.",
        diff: "E",
      },
      {
        q: "Which of the following represents a <b>default argument</b> in a function?",
        options: ["def f(x):", "def f(x=10):", "def f(*x):", "def f(**x):"],
        answer: 1,
        explain: "Default arguments use <code>=</code> in the parameter list.",
        diff: "E",
      },
      {
        q: "Which of the following represents <b>variable-length positional arguments</b>?",
        options: ["*args", "**kwargs", "arg", "&args"],
        answer: 0,
        explain: "<code>*args</code> packs positional arguments into a tuple.",
        diff: "E",
      },
      {
        q: "Which of the following represents <b>variable-length keyword arguments</b>?",
        options: ["*args", "**kwargs", "kwargs", "#args"],
        answer: 1,
        explain: "<code>**kwargs</code> packs keyword arguments into a dictionary.",
        diff: "E",
      },
      {
        q: "A function calling itself is known as:",
        options: ["Iteration", "Recursion", "Composition", "Looping"],
        answer: 1,
        explain: "Recursion is when a function calls itself, typically with a base case.",
        diff: "E",
      },
      {
        q: "Which keyword is used to create an anonymous function in Python?",
        options: ["def", "lambda", "anon", "function"],
        answer: 1,
        explain: "<code>lambda</code> creates a small anonymous function in a single expression.",
        diff: "E",
      },
      {
        q: "What is the scope of a variable defined outside all functions called?",
        options: ["Local scope", "Built-in scope", "Global scope", "Enclosed scope"],
        answer: 2,
        explain: "Variables at the top level of a module are in global scope.",
        diff: "E",
      },
      {
        q: "Which keyword is used to declare a variable as global inside a function?",
        options: ["static", "public", "global", "extern"],
        answer: 2,
        explain: "The <code>global</code> keyword lets you assign to a module-level variable from inside a function.",
        diff: "E",
      },
      {
        q: "What does <code>len()</code> function return?",
        options: ["Number of bytes", "Number of elements", "Number of words", "Type of object"],
        answer: 1,
        explain: "<code>len()</code> returns the number of items in an object.",
        diff: "E",
      },
      {
        q: "In <code>def f(a, b=5):</code>, <code>b</code> is called:",
        options: ["Positional argument", "Keyword argument", "Default argument", "Variable argument"],
        answer: 2,
        explain: "<code>b=5</code> assigns a default value if no argument is passed.",
        diff: "E",
      },
      {
        q: "What is the output of <code>lambda x: x*2</code> when called with <code>(5)</code>?",
        options: ["5", "10", "25", "Error"],
        answer: 1,
        explain: "The lambda doubles its input: 5*2 = 10.",
        diff: "E",
      },
      {
        q: "<pre>def greet(name=\"Guest\"):\n    print(\"Hello\", name)\ngreet()</pre>What is the output?",
        options: ["Hello Guest", "Hello name", "Hello", "Error"],
        answer: 0,
        explain: "No argument passed, default value 'Guest' is used.",
        diff: "M",
      },
      {
        q: "<pre>def add(a, b=5):\n    return a + b\nprint(add(3))</pre>What is the output?",
        options: ["8", "3", "5", "Error"],
        answer: 0,
        explain: "<code>add(3)</code> uses default b=5 → returns 3+5 = 8.",
        diff: "M",
      },
      {
        q: "<pre>def func(*args):\n    return len(args)\nprint(func(1, 2, 3, 4))</pre>What is the output?",
        options: ["3", "4", "5", "Error"],
        answer: 1,
        explain: "<code>*args</code> collects 4 positional arguments, so <code>len(args)</code> = 4.",
        diff: "M",
      },
      {
        q: "<pre>def func(**kwargs):\n    return len(kwargs)\nprint(func(a=1, b=2, c=3))</pre>What is the output?",
        options: ["1", "2", "3", "Error"],
        answer: 2,
        explain: "<code>**kwargs</code> collects 3 keyword arguments into a dict of length 3.",
        diff: "M",
      },
      {
        q: "<pre>def f(x, y=2, z=3):\n    return x + y + z\nprint(f(1, z=10))</pre>What is the output?",
        options: ["6", "13", "14", "Error"],
        answer: 1,
        explain: "x=1, y=2 (default), z=10 → sum = 13.",
        diff: "M",
      },
      {
        q: "<pre>square = lambda x: x ** 2\nprint(square(5))</pre>What is the output?",
        options: ["5", "10", "25", "Error"],
        answer: 2,
        explain: "5² = 25.",
        diff: "M",
      },
      {
        q: "<pre>def fact(n):\n    if n == 1:\n        return 1\n    return n * fact(n-1)\nprint(fact(4))</pre>What is the output?",
        options: ["12", "24", "10", "Error"],
        answer: 1,
        explain: "4! = 4×3×2×1 = 24.",
        diff: "M",
      },
      {
        q: "<pre>x = 10\ndef change():\n    global x\n    x = 20\nchange()\nprint(x)</pre>What is the output?",
        options: ["10", "20", "0", "Error"],
        answer: 1,
        explain: "<code>global x</code> makes the assignment affect the module-level x, so x becomes 20.",
        diff: "M",
      },
      {
        q: "<pre>def func(a, b):\n    return a * b\nprint(func(b=3, a=4))</pre>What is the output?",
        options: ["7", "12", "34", "Error"],
        answer: 1,
        explain: "Keyword arguments can be in any order: 4*3 = 12.",
        diff: "M",
      },
      {
        q: "<pre>def outer():\n    x = 10\n    def inner():\n        print(x)\n    inner()\nouter()</pre>What is the output?",
        options: ["10", "Error", "0", "None"],
        answer: 0,
        explain: "Inner function reads x from the enclosing (nonlocal) scope.",
        diff: "M",
      },
      {
        q: "<pre>def f(a, b, /, c, d):\n    return a + b + c + d\nprint(f(1, 2, c=3, d=4))</pre>What is the output?",
        options: ["Error", "10", "1 2 3 4", "6"],
        answer: 1,
        explain: "<code>/</code> makes a and b positional-only. c and d can be keyword. Sum = 1+2+3+4 = 10.",
        diff: "M",
      },
      {
        q: "<pre>def func(x=[]):\n    x.append(1)\n    return x\nprint(func())\nprint(func())</pre>What is the output?",
        options: ["[1] [1]", "[1] [1, 1]", "[1, 1] [1, 1]", "Error"],
        answer: 1,
        explain: "Mutable default argument! The list persists across calls: first [1], then [1,1].",
        diff: "M",
      },
      {
        q: "<pre>def func(x):\n    return x + 1\nprint(func(func(3)))</pre>What is the output?",
        options: ["3", "4", "5", "Error"],
        answer: 2,
        explain: "Inner call: func(3)=4. Outer call: func(4)=5.",
        diff: "H",
      },
      {
        q: "<pre>def fib(n):\n    if n <= 1:\n        return n\n    return fib(n-1) + fib(n-2)\nprint(fib(5))</pre>What is the output?",
        options: ["3", "5", "8", "Error"],
        answer: 1,
        explain: "Fibonacci: 0,1,1,2,3,<b>5</b>. fib(5)=5.",
        diff: "H",
      },
      {
        q: "<pre>x = 5\ndef f():\n    x = 10\n    print(x)\nf()\nprint(x)</pre>What is the output?",
        options: ["10 5", "5 10", "10 10", "5 5"],
        answer: 0,
        explain: "Inside f, x is a local variable (10). Outside, the global x is still 5.",
        diff: "H",
      },
      {
        q: "<pre>add = lambda x, y: x + y\nprint(add(\"Hello\", \"World\"))</pre>What is the output?",
        options: ["Hello World", "HelloWorld", "Error", "Hello+World"],
        answer: 1,
        explain: "<code>+</code> on two strings concatenates them without a space.",
        diff: "H",
      },
      {
        q: "<pre>def func(a, b=2, *args):\n    return a + b + len(args)\nprint(func(1, 3, 5, 7))</pre>What is the output?",
        options: ["5", "6", "7", "Error"],
        answer: 1,
        explain: "a=1, b=3 (passed), *args = (5,7) → len=2. Sum = 1+3+2 = 6.",
        diff: "H",
      },
      {
        q: "<pre>def power(x, n=2):\n    return x ** n\nprint(power(2, n=3))</pre>What is the output?",
        options: ["4", "8", "9", "Error"],
        answer: 1,
        explain: "<code>n=3</code> keyword argument overrides the default. 2³ = 8.",
        diff: "H",
      },
    ],
  },
  topic4: {
    name: "Text File and Binary File Handling",
    questions: [
      {
        q: "Which mode is used to open a file for <b>reading</b> in Python?",
        options: ['"w"', '"r"', '"a"', '"x"'],
        answer: 1,
        explain: "<code>'r'</code> opens a file for reading (default mode).",
        diff: "E",
      },
      {
        q: 'Which mode opens a file for <b>writing</b>, creating it if it does not exist, and <b>truncating</b> if it exists?',
        options: ['"r"', '"a"', '"w"', '"x"'],
        answer: 2,
        explain: "<code>'w'</code> creates the file or truncates an existing one to zero length.",
        diff: "E",
      },
      {
        q: "Which mode opens a file in <b>append</b> mode?",
        options: ['"r"', '"w"', '"a"', '"rw"'],
        answer: 2,
        explain: "<code>'a'</code> opens for writing, appending at the end if the file exists.",
        diff: "E",
      },
      {
        q: "Which mode is used to open a file in <b>binary</b> mode?",
        options: ['"b"', '"t"', '"rb"', '"wb"'],
        answer: 2,
        explain: "Append <code>'b'</code> for binary mode (e.g., <code>'rb'</code>, <code>'wb'</code>).",
        diff: "E",
      },
      {
        q: "Which function is used to read the <b>entire content</b> of a file as a string?",
        options: ["readline()", "read()", "readlines()", "readall()"],
        answer: 1,
        explain: "<code>read()</code> reads the entire file (or n bytes if specified).",
        diff: "E",
      },
      {
        q: "Which method is used to write a string to a file?",
        options: ["write()", "writeline()", "writeall()", "put()"],
        answer: 0,
        explain: "<code>file.write(string)</code> writes the given string to the file.",
        diff: "E",
      },
      {
        q: "Which Python module is used to handle <b>CSV</b> files?",
        options: ["pickle", "csv", "os", "file"],
        answer: 1,
        explain: "The built-in <code>csv</code> module provides reader/writer for CSV files.",
        diff: "E",
      },
      {
        q: "Which Python module is used to serialize and deserialize objects?",
        options: ["json", "pickle", "csv", "os"],
        answer: 1,
        explain: "<code>pickle</code> serializes Python objects to bytes and back.",
        diff: "E",
      },
      {
        q: "Which method returns the <b>current position</b> of the file pointer?",
        options: ["seek()", "tell()", "pos()", "where()"],
        answer: 1,
        explain: "<code>tell()</code> returns the file pointer's current byte offset.",
        diff: "E",
      },
      {
        q: "Which method is used to <b>move the file pointer</b> to a specific position?",
        options: ["move()", "seek()", "goto()", "jump()"],
        answer: 1,
        explain: "<code>seek(offset)</code> moves the file pointer to a given byte offset.",
        diff: "E",
      },
      {
        q: "What does <code>f.close()</code> do?",
        options: ["Deletes the file", "Closes the file and frees resources", "Saves the file", "Opens the file"],
        answer: 1,
        explain: "<code>close()</code> flushes buffers and releases the OS handle.",
        diff: "E",
      },
      {
        q: "Which method reads a <b>single line</b> from a file?",
        options: ["read()", "readline()", "readlines()", "nextline()"],
        answer: 1,
        explain: "<code>readline()</code> reads up to and including the next newline.",
        diff: "E",
      },
      {
        q: "<pre>f = open(\"data.txt\", \"w\")\nf.write(\"Hello\")\nf.close()</pre>Assuming the file did not exist before. What happens?",
        options: ["\"Hello\" is printed on screen", '"Hello" is written to data.txt', "File is deleted", "Error"],
        answer: 1,
        explain: "Write mode creates/overwrites the file and writes the string to it.",
        diff: "M",
      },
      {
        q: "<pre>f = open(\"data.txt\", \"r\")\nprint(f.readline())</pre>If data.txt contains: Line1\\nLine2\\nWhat is printed?",
        options: ["Line1\\nLine2", "Line1", "Line2", "Line1\\n"],
        answer: 3,
        explain: "<code>readline()</code> reads up to and <i>including</i> the newline → 'Line1\\n'.",
        diff: "M",
      },
      {
        q: "<pre>f = open(\"data.txt\", \"w\")\nf.writelines([\"A\", \"B\", \"C\"])\nf.close()</pre>What is in the file?",
        options: ["ABC\\n", "A B C", "ABC", "[A, B, C]"],
        answer: 2,
        explain: "<code>writelines()</code> writes each string as-is — no separator or newline added.",
        diff: "M",
      },
      {
        q: "<pre>f = open(\"data.txt\", \"rb\")\ndata = f.read()\nprint(type(data))</pre>What is the type of data?",
        options: ["str", "bytes", "list", "bytearray"],
        answer: 1,
        explain: "Reading a file in binary mode returns <code>bytes</code> objects.",
        diff: "M",
      },
      {
        q: "<pre>import pickle\nd = {\"a\": 1}\ndata = pickle.dumps(d)\nprint(type(data))</pre>What is the output?",
        options: ["dict", "str", "bytes", "list"],
        answer: 2,
        explain: "<code>pickle.dumps()</code> returns a <code>bytes</code> object.",
        diff: "M",
      },
      {
        q: "<pre>f = open(\"data.txt\", \"r\")\nf.seek(5)\nprint(f.tell())</pre>What is the output?",
        options: ["0", "5", "Error", "1"],
        answer: 1,
        explain: "<code>seek(5)</code> moves to byte 5, and <code>tell()</code> reports the current position.",
        diff: "M",
      },
      {
        q: "<pre>with open(\"data.txt\", \"r\") as f:\n    data = f.read()\nprint(data)</pre>What is the output?",
        options: ["The file content", "Error", "None", "Empty"],
        answer: 0,
        explain: "<code>with</code> block reads the file, then <code>print(data)</code> outputs its content.",
        diff: "M",
      },
      {
        q: "<pre>import csv\nwith open(\"data.csv\", \"r\") as f:\n    r = csv.reader(f)\n    print(next(r))</pre>If data.csv contains 'a,b,c', what is the output?",
        options: ["a,b,c", "['a', 'b', 'c']", "abc", "Error"],
        answer: 1,
        explain: "<code>csv.reader</code> yields each row as a list of strings.",
        diff: "M",
      },
      {
        q: "<pre>f = open(\"test.txt\", \"w\")\nf.write(\"Python\")\nf.seek(0)\nprint(f.read())</pre>What is the output?",
        options: ["Python", "Empty string", "PythonPython", "Error"],
        answer: 3,
        explain: "After opening in write mode, the file is not readable. <code>read()</code> on a write-only handle raises <code>io.UnsupportedOperation</code>.",
        diff: "M",
      },
      {
        q: "<pre>import pickle\nl = [1, 2, 3]\nwith open(\"data.pkl\", \"wb\") as f:\n    pickle.dump(l, f)</pre>What does this code do?",
        options: ["Writes list as text", "Serializes and writes list to binary file", "Reads list", "Error"],
        answer: 1,
        explain: "<code>pickle.dump(obj, file)</code> writes the serialized object to a binary file.",
        diff: "M",
      },
      {
        q: "<pre>f = open(\"a.txt\", \"r\")\nprint(f.read(3))</pre>If a.txt contains 'Hello World', what is printed?",
        options: ["Hel", "Hello", "Hello W", "Hel"],
        answer: 0,
        explain: "<code>read(3)</code> reads only the first 3 characters → 'Hel'.",
        diff: "M",
      },
      {
        q: "<pre>import csv\nwith open(\"data.csv\", \"w\", newline=\"\") as f:\n    w = csv.writer(f)\n    w.writerow([1, 2, 3])</pre>What is written to file?",
        options: ["1,2,3\\n", "[1,2,3]", "123", "1 2 3"],
        answer: 0,
        explain: "<code>writerow</code> writes the list as comma-separated values followed by a line terminator.",
        diff: "M",
      },
      {
        q: "<pre>f = open(\"data.txt\", \"w\")\nf.write(\"Hello\\nWorld\")\nf.close()\nf = open(\"data.txt\", \"r\")\nprint(f.readlines())</pre>What is the output?",
        options: ["['Hello\\\\nWorld']", "['Hello\\n', 'World']", "'Hello\\\\nWorld'", "['Hello', 'World']"],
        answer: 1,
        explain: "<code>readlines()</code> splits on newlines and keeps them in each line.",
        diff: "H",
      },
      {
        q: "<pre>import pickle\nd = {\"x\": 10}\nwith open(\"d.pkl\", \"wb\") as f:\n    pickle.dump(d, f)\nwith open(\"d.pkl\", \"rb\") as f:\n    obj = pickle.load(f)\nprint(obj[\"x\"])</pre>What is the output?",
        options: ["10", '{"x": 10}', "Error", "None"],
        answer: 0,
        explain: "<code>pickle.load</code> reconstructs the original dict; obj['x'] = 10.",
        diff: "H",
      },
      {
        q: "<pre>f = open(\"a.txt\", \"a+\")\nf.write(\"Hi\")\nf.seek(0)\nprint(f.read())</pre>What is the output?",
        options: ["Hi", "Empty", "Error", "None"],
        answer: 0,
        explain: "<code>'a+'</code> allows both appending and reading. After seek(0), it reads the entire file.",
        diff: "H",
      },
      {
        q: "<pre>f = open(\"a.txt\", \"w\")\nf.write(\"0123456789\")\nf.close()\nf = open(\"a.txt\", \"r\")\nf.seek(3)\nprint(f.read(2))</pre>What is the output?",
        options: ["34", "01", "23", "Error"],
        answer: 0,
        explain: "<code>seek(3)</code> positions at '3', then <code>read(2)</code> returns '34'.",
        diff: "H",
      },
      {
        q: "<pre>import csv\nwith open(\"data.csv\", \"w\", newline=\"\") as f:\n    w = csv.writer(f)\n    w.writerows([[1, 2], [3, 4]])</pre>What is in the file?",
        options: ["1,2\\n3,4\\n", "1 2 3 4", "[[1,2],[3,4]]", "1234"],
        answer: 0,
        explain: "<code>writerows</code> writes each sublist as a row.",
        diff: "H",
      },
      {
        q: "<pre>import pickle\nwith open(\"a.pkl\", \"wb\") as f:\n    pickle.dump([1, 2, 3], f)\nf = open(\"a.pkl\", \"rb\")\ndata = pickle.load(f)\nf.close()\nprint(sum(data))</pre>What is the output?",
        options: ["6", "[1, 2, 3]", "Error", "0"],
        answer: 0,
        explain: "<code>sum([1,2,3]) = 6</code>.",
        diff: "H",
      },
    ],
  },
};